import React from 'react'

const TermsAndCond = () => {
  return (
    <div className='p-20 '>
      <div className='mb-5 shadow-md p-1 flex flex-col'>
        <h1 className='text-4xl p-2 items-center'>Terms & Condition</h1>
        <p className='p-2 font-normal text-slate-800'>please read all of our terms and conditions before doing anything.</p>
      </div>
      <div className='mb-5 p-2 flex flex-col p-1'>
        <p className='font-medium  text-slate-800 mb-11'>Terms and condition</p>
        <h2 className='font-medium  text-slate-800'>MEDIMENTOR - TERMS AND CONDITION</h2>
      </div>
      <div className='mb-5 p-2 flex flex-col p-1  text-slate-900'>
        <p>This document (“Terms”) is an electronic record in terms of The Information Technology Act, 2000, and rules thereunder, as applicable, and the amended provisions pertaining to electronic records in various statutes, as amended from time to time by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
        <p>This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021 as amended from time to time, which requires publishing of the rules and regulations, privacy policy and Terms for access or usage of www.medimentor.com website and its mobile application.</p>
      </div>
      <div className='mb-5 p-2 flex flex-col p-1  text-slate-900'>
        <h1 className='mb-5 font-medium'>GENERAL</h1>
        <p className='mb-4'>
            Our Platform is operated, and services are provided in compliance with the laws in India and AHL shall not be liable to provide any Services availed by you in locations outside India. If you access our services from locations outside India, you do so at your own risk and you are solely liable for compliance with applicable local laws. The User agrees to use the service to authorize an individual and get the services from the third party on his/her behalf. Where you use any third-party website or the services of any third party, you may be subject to alternative or additional terms and conditions of use and privacy policies of the respective third party/s.
        </p>
        <ol className='list-disc'>
            <li className='ml-[27px] mb-3'>
                <p className='text-align-justify'>
                    <span>You are solely responsible for the medical, health, and personal information you provide on the Platform, and You are requested to use Your discretion in providing such information.</span>
                </p>
            </li>
            <li className='ml-[27px] mb-3'>
                <p>
                    <span>If Your age is below that of 18 years, your parents or legal guardians can transact on behalf of You if they are registered users. You are prohibited from purchasing any material the sale or purchase of which to/by minors is prohibited and which is for consumption by adults only.</span>
                </p>
            </li>
            <li className='ml-[27px] mb-3'>
                <p>
                    <span>
                    You are legally competent to contract, and otherwise competent to receive the Services (as defined in these Terms and Conditions). Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents, etc. are not eligible to use the Platform.       
                    </span>
                </p>
            </li>
            <li className='ml-[27px] mb-3'>
                <p>
                    <span>Your registered id can only be utilized by You wherein Your details have been provided and We do not permit multiple persons to share a single login/ registration id.  </span>
                </p>
            </li>
            <li className='ml-[27px] mb-3'>
                <p>
                    <span>
                    Organizations, companies, and businesses may not become registered Users on the Platform or use the Platform through individual Users.
                    </span>
                </p>
            </li>
        </ol>
      </div>
    </div>
  )
}

export default TermsAndCond
